thaigram/urls.py
from django.contrib import admin
from django.urls import path
from images import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('explore', views.explore, name='explore'),
    path('profile', views.profile, name='profile'),
    path('upload', views.upload, name='upload'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models
from django.contrib.auth.models import User


class Image(models.Model):

    file = models.FileField()
    location = models.CharField(max_length=80)
    caption = models.TextField(unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.location} - {self.caption}'


class Comment(models.Model):

    message = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_for = models.ForeignKey(Image, on_delete=models.CASCADE, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.created_by.username} - {self.created_for.caption}'


class Like(models.Model):

    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_for = models.ForeignKey(Image, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.created_by.username} - {self.created_for.caption}'

images/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Image
from django.shortcuts import redirect
# Create your views here.


def index(request):
    user = request.user
    if user.is_authenticated:
        all_images = Image.objects.all().order_by('-created_at')
        return render(request, 'feed.html', context={
            'images': all_images
        })
    else:
        return render(request, 'login.html')


def profile(request):
    user = request.user
    if user.is_authenticated:
        return render(request, 'profile.html')
    else:
        return HttpResponse('You have to log in')


def explore(request):
    user = request.user
    if user.is_authenticated:
        return HttpResponse('You have reached the explore!')
    else:
        return HttpResponse('You have to log in')


def upload(request):
    if request.method == 'POST':
        user = request.user
        if user.is_authenticated:
            location = request.POST.get('location')
            caption = request.POST.get('caption'),
            uploaded_file = request.FILES.get('file')
            Image.objects.create(
                file=uploaded_file,
                location=location,
                caption=caption,
                created_by=user,
            )
            return redirect('/')
        else:
            return HttpResponse('You have to log in')
    else:
        return HttpResponse('Nothing to see here')

images/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title%}{% endblock%} | Thaigram</title>

</head>

<body>
    {% if user.is_authenticated %}
        {% include "partials/header.html" %}
    {% endif %}
    
    {% block content %}{% endblock%} 
    
    {% include "partials/footer.html"%}
</body>

</html>

images/templates/feed.html
{% extends "base.html" %}
{% load static %}

{% block title%}Feed{% endblock%}

{% block content %}
<main class="feed">


    <form action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="file" required>
            <input type="text" name="location" required placeholder="Location">
            <input type="text" name="caption" required placeholder="Caption">
            <input type="submit" value="Upload photo">
    </form>

    {% for image in images %}
    <div class="photo">
        <header class="photo__header">
            <img src="{% static 'images/avatar.jpg' %}" class="photo__avatar">
            <div class="photo__user">
                <span class="photo__username">{{image.created_by.username}}</span>
                <span class="photo__location">{{image.location}}</span>
            </div>
        </header>
        <img src="media/{{image.file}}" class="photo__file">
        <div class="photo__meta">
            <div class="photo__actions">
                <div class="photo__action-column">
                    <span class="photo__action">
                        <i class="fa fa-heart-o"></i>
                    </span>
                    <span class="photo__action">
                        <i class="fa fa-comment-o"></i>
                    </span>
                </div>
                <span class="photo__action">
                    <i class="fa fa-bookmark-o"></i>
                </span>
            </div>
            <span class="photo__likes">{{image.like_set.all.count}} likes</span>
            <ul class="photo__comments">
                <li class="photo__comment">
                    <span class="photo__comment-author">
                        {{image.created_by.username}}
                    </span>
                    {{image.caption}}
                </li>
                {% for comment in image.comment_set.all %}
                <li class="photo__comment">
                    <span class="photo__comment-author">
                        {{comment.created_by.username}}
                    </span>
                    {{comment.message}}
                </li>
                {% endfor %}
            </ul>
            <span class="photo__date">{{image.created_at}}</span>
            <div class="photo__add-comment">
                <textarea placeholder="Add a comment..."></textarea>
                <i class="fa fa-ellipsis-h"></i>
            </div>
        </div>
    </div>
    {% endfor %}

</main>
{% endblock %}

images/templates/login.html
{% extends "base.html" %}

{% block title%}Log in{% endblock%}

{% block content %}
<main class="login">
    <div class="login__column">
        <img src="images/phoneImage.png" alt="Phone" title="Phone">
    </div>
    <div class="login__column">
        <div class="login__box">

            <img src="images/logo.png" alt="Logo" class="login__logo">

            <form action="feed.html" method="get" class="login__form">
                <input placeholder="Username" type="text" name="username" required="required">
                <input placeholder="Password" type="password" name="password" required="required">
                <input type="submit" value="Log In">
            </form>

            <span class="login__or">or</span>

            <a href="#" class="login__link login__link--dark">
                <i class="fa fa-facebook-square"></i>
                Login with Facebook</a>
            <a href="#" class="login__link login__link--dark login__link--small">Forgot password</a>



        </div>

        <div class="login__box">
            <span>Don't have an account?</span>
            <a href="#" class="login__link">Sign up</a>
        </div>

        <div class="login__box login__box--transparent">
            <span>Get the app.</span>
            <div class="login__appstores">
                <img src="images/ios.png" alt="" class="login__appstore">
                <img src="images/android.png" alt="" class="login__appstore">
            </div>
        </div>
    </div>
</main>
{% endblock %}

images/templates/partials/footer.html
<footer class="footer">
    <div class="footer__column">
        <nav class="footer__navigation">
            <ul class="footer__list">
                <li class="footer__list-item">
                    <a href="#" class="footer__link">About</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Support</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Blog</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Press</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Api</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Jobs</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Privacy</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Terms</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Directory</a>
                </li>
                <li class="footer__list-item">
                    <a href="#" class="footer__link">Language</a>
                </li>
            </ul>
        </nav>
    </div>
    <div class="footer__column">
        <span class="footer__copy">© 2018 Thaigram</span>
    </div>
</footer>

images/templates/partials/header.html
{% load static %}
<header class="header">
    <div class="header__container">
        <div class="header__logo">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/logo.png' %}" class="header__image">
            </a>
        </div>
        <form>
            <input type="text" placeholder="Search">
        </form>
        <nav class="header__navigation">
            <ul class="header__list">
                <li class="header__list-item">
                    <a href="{% url 'explore' %}" class="header__link">
                        <i class="fa fa-compass" aria-hidden="true"></i>
                    </a>
                </li>
                <li class="header__list-item">
                    <a href="#" class="header__link">
                        <i class="fa fa-heart-o"></i>
                    </a>
                </li>
                <li class="header__list-item">
                    <a href="{% url 'profile' %}" class="header__link">
                        <i class="fa fa-user-o"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</header>